### Get all contacts
### Local
GET http://localhost:8080/contacts


### Render
GET https://cse341-ic-project1.onrender.com/contacts

### Get contact by id

GET http://localhost:8080/contacts/6a56f82f77a2db5f6d84df53