### Get all contacts
### Local
GET http://localhost:8080/contacts


### Render
GET https://cse341-ic-project1.onrender.com/contacts

### Get contact by id

GET http://localhost:8080/contacts/6a56f82f77a2db5f6d84df53

### Render
GET https://cse341-ic-project1.onrender.com/contacts/6a56f82f77a2db5f6d84df53

### Create contact

POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName":"Peter",
    "lastName":"Parker",
    "email":"peter@marvel.com",
    "favoriteColor":"Red",
    "birthday":"2001-08-10"
}

### Update contact

PUT http://localhost:8080/contacts/6a56f82f77a2db5f6d84df53
Content-Type: application/json

{
    "firstName":"Luis",
    "lastName":"Chulde",
    "email":"ivan@gmail.com",
    "favoriteColor":"Red",
    "birthday":"1992-12-19"
}

### Delete contact

DELETE http://localhost:8080/contacts/6a56f82f77a2db5f6d84df57